'use client';
import Link from 'next/link';
import { FormEvent,useEffect,useState } from 'react';
import { UserPlus } from 'lucide-react';
import { AuthShell } from '@/components/auth-shell'; import { Alert } from '@/components/ui/alert'; import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Label } from '@/components/ui/label'; import { createBrowserSupabaseClient } from '@/lib/supabase/browser';
export default function SignupPage(){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[confirmPassword,setConfirmPassword]=useState('');const[error,setError]=useState<string|null>(null);const[confirmationSent,setConfirmationSent]=useState(false);const[loading,setLoading]=useState(false);const[loginHref,setLoginHref]=useState('/login');useEffect(()=>setLoginHref(`/login${window.location.search}`),[]);
async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError(null);if(password!==confirmPassword){setError('Passwords do not match.');return;}setLoading(true);const next=new URLSearchParams(window.location.search).get('next');const destination=next?.startsWith('/')&&!next.startsWith('//')?next:'/report';const{data,error:signupError}=await createBrowserSupabaseClient().auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}${destination}`}});if(signupError){setError(signupError.message);setLoading(false);return;}if(data.user&&data.user.identities?.length===0){setError('An account with this email already exists. Please sign in instead.');setLoading(false);return;}if(data.session){window.location.assign(destination);return;}setConfirmationSent(true);setLoading(false);}
if(confirmationSent)return <AuthShell title="Check your email" description="One more step to activate your account."><Alert variant="success" role="status">Your account was created. Open the confirmation link sent to <b>{email}</b>.</Alert><Link className="mt-6 block text-center text-sm font-semibold text-blue-800 hover:underline" href={loginHref}>Return to sign in</Link></AuthShell>;
return <AuthShell title="Create an account" description="Register to report facility issues.">{error&&<Alert role="alert" className="mb-5">{error}</Alert>}<form className="space-y-5" onSubmit={submit}><div><Label htmlFor="email">Email address</Label><Input id="email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></div><div><Label htmlFor="password">Password</Label><Input id="password" type="password" autoComplete="new-password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/><p className="mt-1.5 text-xs text-slate-500">Use at least 8 characters.</p></div><div><Label htmlFor="confirmPassword">Confirm password</Label><Input id="confirmPassword" type="password" autoComplete="new-password" minLength={8} required value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></div><Button className="w-full" size="lg" disabled={loading}><UserPlus className="size-4"/>{loading?'Creating account…':'Create account'}</Button></form><p className="mt-6 text-center text-sm text-slate-600">Already registered? <Link className="font-semibold text-blue-800 hover:underline" href={loginHref}>Sign in</Link></p></AuthShell>}
